import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Japanese 폴더용 사이드바 (docs/japanese 폴더를 자동 인식)
  japaneseSidebar: [{type: 'autogenerated', dirName: 'Japanese'}],
  
  // English 폴더용 사이드바 (docs/english 폴더를 자동 인식)
  englishSidebar: [{type: 'autogenerated', dirName: 'English'}],
};

export default sidebars;