import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 자동으로 docs 폴더 내의 모든 파일을 메뉴로 생성하는 설정입니다.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;